spring:
  application:
    name: music-batch

  batch:
    initialize-schema: always

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  logging:
    level:
      org.springframework.batch: DEBUG
      org.hibernate.SQL: DEBUG