CREATE TABLE MUSIC (
    music_id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    ins_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ins_oprt VARCHAR(50) DEFAULT 'anonymous' NOT NULL,
    upd_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    upd_oprt VARCHAR(50) DEFAULT 'anonymous' NOT NULL
);

CREATE TABLE SCOREBOARD (
    scoreboard_id INT PRIMARY KEY AUTO_INCREMENT,
    music_id INT,
    score INT,
    ins_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ins_oprt VARCHAR(50) DEFAULT 'anonymous' NOT NULL,
    upd_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    upd_oprt VARCHAR(50) DEFAULT 'anonymous' NOT NULL
);

CREATE TABLE SCOREBOARD_HISTORY (
    scoreboard_history_id INT PRIMARY KEY AUTO_INCREMENT,
    scoreboard_id INT,
    music_id INT,
    score INT,
    ins_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ins_oprt VARCHAR(50) DEFAULT 'anonymous' NOT NULL,
    upd_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    upd_oprt VARCHAR(50) DEFAULT 'anonymous' NOT NULL
);