INSERT INTO MUSIC (music_id, title, artist) VALUES (1, '24K Magic', 'Bruno Mars');
INSERT INTO MUSIC (music_id, title, artist) VALUES (2, 'Shake It Off', 'Taylor Swift');
INSERT INTO MUSIC (music_id, title, artist) VALUES (3, 'APT.', 'ROSE, Bruno Mars');
INSERT INTO MUSIC (music_id, title, artist) VALUES (4, 'twilight zone', 'Ariana Grande');
INSERT INTO MUSIC (music_id, title, artist) VALUES (5, 'Ordinary', 'Alex Warren');
INSERT INTO MUSIC (music_id, title, artist) VALUES (6, 'Beautiful Things', 'Benson Boone');
INSERT INTO MUSIC (music_id, title, artist) VALUES (7, 'Sailor Song', 'Gigi Perez');
INSERT INTO MUSIC (music_id, title, artist) VALUES (8, 'Sports car', 'Tate McRae');
INSERT INTO MUSIC (music_id, title, artist) VALUES (9, 'Who', 'Jimin');
INSERT INTO MUSIC (music_id, title, artist) VALUES (10, 'Abracadabra', 'Lady Gaga');
INSERT INTO MUSIC (music_id, title, artist) VALUES (11, 'Lose Control', 'Teddy Swims');
INSERT INTO MUSIC (music_id, title, artist) VALUES (12, 'Pink Pony Club', 'Chappell Roan');
INSERT INTO MUSIC (music_id, title, artist) VALUES (13, 'Up From the Bottom', 'Linkin Park');
INSERT INTO MUSIC (music_id, title, artist) VALUES (14, 'MONA LISA', 'j-hope');
INSERT INTO MUSIC (music_id, title, artist) VALUES (15, 'blue', 'yung kai');
INSERT INTO MUSIC (music_id, title, artist) VALUES (16, 'Iris', 'The Goo Goo Dolls');
INSERT INTO MUSIC (music_id, title, artist) VALUES (17, 'Tate', 'Sabrina Carpenter');
INSERT INTO MUSIC (music_id, title, artist) VALUES (18, 'Si Antes Te Hubiera Conocido', 'KAROL G');
INSERT INTO MUSIC (music_id, title, artist) VALUES (19, 'WILDFLOWER', 'Billie Eilish');
INSERT INTO MUSIC (music_id, title, artist) VALUES (20, 'Yellow', 'Coldplay');

INSERT INTO SCOREBOARD (music_id, score) VALUES (1, 143);
INSERT INTO SCOREBOARD (music_id, score) VALUES (2, 98);
INSERT INTO SCOREBOARD (music_id, score) VALUES (3, 43);
INSERT INTO SCOREBOARD (music_id, score) VALUES (4, 11);
INSERT INTO SCOREBOARD (music_id, score) VALUES (5, 105);
INSERT INTO SCOREBOARD (music_id, score) VALUES (6, 71);
INSERT INTO SCOREBOARD (music_id, score) VALUES (7, 41);
INSERT INTO SCOREBOARD (music_id, score) VALUES (8, 19);
INSERT INTO SCOREBOARD (music_id, score) VALUES (9, 88);
INSERT INTO SCOREBOARD (music_id, score) VALUES (10, 30);
INSERT INTO SCOREBOARD (music_id, score) VALUES (11, 53);
INSERT INTO SCOREBOARD (music_id, score) VALUES (12, 21);
INSERT INTO SCOREBOARD (music_id, score) VALUES (13, 111);
INSERT INTO SCOREBOARD (music_id, score) VALUES (14, 29);
INSERT INTO SCOREBOARD (music_id, score) VALUES (15, 38);
INSERT INTO SCOREBOARD (music_id, score) VALUES (16, 78);
INSERT INTO SCOREBOARD (music_id, score) VALUES (17, 5);
INSERT INTO SCOREBOARD (music_id, score) VALUES (18, 12);
INSERT INTO SCOREBOARD (music_id, score) VALUES (19, 2);
INSERT INTO SCOREBOARD (music_id, score) VALUES (20, 96);