INSERT INTO MUSIC (title, artist) VALUES ('24K Magic', 'Bruno Mars');
INSERT INTO MUSIC (title, artist) VALUES ('Shake It Off', 'Taylor Swift');
INSERT INTO MUSIC (title, artist) VALUES ('APT.', 'ROSE, Bruno Mars');
INSERT INTO MUSIC (title, artist) VALUES ('twilight zone', 'Ariana Grande');
INSERT INTO MUSIC (title, artist) VALUES ('Ordinary', 'Alex Warren');
INSERT INTO MUSIC (title, artist) VALUES ('Beautiful Things', 'Benson Boone');
INSERT INTO MUSIC (title, artist) VALUES ('Sailor Song', 'Gigi Perez');
INSERT INTO MUSIC (title, artist) VALUES ('Sports car', 'Tate McRae');
INSERT INTO MUSIC (title, artist) VALUES ('Who', 'Jimin');
INSERT INTO MUSIC (title, artist) VALUES ('Abracadabra', 'Lady Gaga');
INSERT INTO MUSIC (title, artist) VALUES ('Lose Control', 'Teddy Swims');
INSERT INTO MUSIC (title, artist) VALUES ('Pink Pony Club', 'Chappell Roan');
INSERT INTO MUSIC (title, artist) VALUES ('Up From the Bottom', 'Linkin Park');
INSERT INTO MUSIC (title, artist) VALUES ('MONA LISA', 'j-hope');
INSERT INTO MUSIC (title, artist) VALUES ('blue', 'yung kai');
INSERT INTO MUSIC (title, artist) VALUES ('Iris', 'The Goo Goo Dolls');
INSERT INTO MUSIC (title, artist) VALUES ('Tate', 'Sabrina Carpenter');
INSERT INTO MUSIC (title, artist) VALUES ('Si Antes Te Hubiera Conocido', 'KAROL G');
INSERT INTO MUSIC (title, artist) VALUES ('WILDFLOWER', 'Billie Eilish');
INSERT INTO MUSIC (title, artist) VALUES ('Yellow', 'Coldplay');

INSERT INTO SCOREBOARD (music_id, score) VALUES (1, 143);
INSERT INTO SCOREBOARD (music_id, score) VALUES (2, 98);
INSERT INTO SCOREBOARD (music_id, score) VALUES (3, 43);
INSERT INTO SCOREBOARD (music_id, score) VALUES (4, 11);
INSERT INTO SCOREBOARD (music_id, score) VALUES (5, 105);
INSERT INTO SCOREBOARD (music_id, score) VALUES (6, 71);
INSERT INTO SCOREBOARD (music_id, score) VALUES (7, 41);
INSERT INTO SCOREBOARD (music_id, score) VALUES (8, 19);
INSERT INTO SCOREBOARD (music_id, score) VALUES (9, 88);
INSERT INTO SCOREBOARD (music_id, score) VALUES (10, 30);
INSERT INTO SCOREBOARD (music_id, score) VALUES (11, 53);
INSERT INTO SCOREBOARD (music_id, score) VALUES (12, 21);
INSERT INTO SCOREBOARD (music_id, score) VALUES (13, 111);
INSERT INTO SCOREBOARD (music_id, score) VALUES (14, 29);
INSERT INTO SCOREBOARD (music_id, score) VALUES (15, 38);
INSERT INTO SCOREBOARD (music_id, score) VALUES (16, 78);
INSERT INTO SCOREBOARD (music_id, score) VALUES (17, 5);
INSERT INTO SCOREBOARD (music_id, score) VALUES (18, 12);
INSERT INTO SCOREBOARD (music_id, score) VALUES (19, 2);
INSERT INTO SCOREBOARD (music_id, score) VALUES (20, 96);